### ISSUE TITLE
JDK 9+ Compatibility

### ISSUE THREAD

**Issue by Nikas10** [akvone/update-image-maven-plugin#1]
Plugin throws exceptions during execution on JDK 11.
java.lang.NoClassDefFoundError: javax/activation/DataSource
It's possible that it require javax which is cut from JDK 9 and next versions.

**Comment by akvone** [comment]
Yes, I have the same problem.
I'll try to fix it ASAP

**Comment by akvone** [comment]
Fixed in 0.5.3
